apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-ingress
  annotations:
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.annotations.group_name }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations.scheme }}
    alb.ingress.kubernetes.io/target.type: {{ .Values.ingress.annotations.target_type }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.pathType }}
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: {{ .Values.service.app_port }}