apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.ingress.annotations.rewrite_target }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: {{ .Values.ingress.pathType }}
        path: {{ .Values.ingress.path }}
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: {{ .Values.service.app_port }}