version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: python main.py

  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
    command: sleep 10 && pytest test_main.py

