service:
  type: ClusterIP
  app_port: 80
  app_target_port: 5000

ingress:
  host: oddappmoon.moongroup.click ##temp name 
  pathType: Prefix
  ingressClassName: alb
  path: "/"
  annotations: 
    group_name: loadbalancer-moon
    scheme: internet-facing
    target_type: ip

deployment:
  restartPolicy: Always
  replicas: 1
  oddApp:
    repository: "422143002123.dkr.ecr.us-east-1.amazonaws.com/moonactive"
    tag: "latest"
    port: 5000
    imagePullPolicy: IfNotPresent
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200
  strategy:
    type: RollingUpdate
    maxUnavailable: 0
    maxSurge: 1
  sidecar:
    repository: "busybox"
    imagePullPolicy: IfNotPresent
    command: 
      - "/bin/sh"
      - "-c"
      - "while true; do if [ -f /logs/odd-logs.txt ]; then tail -f /logs/odd-logs.txt; else exit 1; fi; done"
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      command: 
        - "/bin/sh"
        - "-c"
        - "if [ -f /logs/odd-logs.txt ]; then exit 0; else exit 1; fi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70

volume:
  name: shared-volume
  emptyDir: {}