service:
  type: ClusterIP
  app_port: 80
  app_target_port: 5000

ingress:
  host: oddappmoon.info ##temp name 
  pathType: Prefix
  ingressClassName: alb
  path: "/"
  annotations: 
    group_name: loadbalancer-moon
    scheme: internet-facing
    target_type: ip

deployment:
  restartPolicy: Always
  replicas: 1
  oddApp:
    repository: "422143002123.dkr.ecr.us-east-1.amazonaws.com/moonactive"
    tag: "23"
    port: 5000
    imagePullPolicy: IfNotPresent
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200
  strategy:
    type: RollingUpdate
    maxUnavailable: 0
    maxSurge: 1

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 70

