name: Lint, Build, and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        env:
          REPO_NAME: your-ecr-repo-name
          AWS_REGION: your-region
        run: |
          IMAGE_TAG=${GITHUB_RUN_NUMBER}  # Use the build number as the tag
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          ECR_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME

          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $ECR_URL:$IMAGE_TAG .
          docker tag $ECR_URL:$IMAGE_TAG $ECR_URL:$IMAGE_TAG

      # - name: Push Docker Image to Amazon ECR
      #   env:
      #     REPO_NAME: your-ecr-repo-name
      #     AWS_REGION: your-region
      #   run: |
      #     IMAGE_TAG=${GITHUB_RUN_NUMBER}  # Use the build number as the tag
      #     AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      #     ECR_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME

      #     echo "Pushing Docker image with tag: $IMAGE_TAG to ECR"
      #     docker push $ECR_URL:$IMAGE_TAG
