name: Lint, Build, and Push to ECR

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEAFULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Tag Docker Image
        env:
          REPO_NAME: your-ecr-repo-name
          AWS_REGION: your-region
        run: |
          IMAGE_TAG=${GITHUB_RUN_NUMBER}  # Use the build number as the tag
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
          ECR_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME

          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build -t $ECR_URL:$IMAGE_TAG .
          docker tag $ECR_URL:$IMAGE_TAG $ECR_URL:$IMAGE_TAG

      # - name: Push Docker Image to Amazon ECR
      #   env:
      #     REPO_NAME: your-ecr-repo-name
      #     AWS_REGION: your-region
      #   run: |
      #     IMAGE_TAG=${GITHUB_RUN_NUMBER}  # Use the build number as the tag
      #     AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
      #     ECR_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME

      #     echo "Pushing Docker image with tag: $IMAGE_TAG to ECR"
      #     docker push $ECR_URL:$IMAGE_TAG
